# Generated by Django 2.0.6 on 2018-06-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名')),
                ('content', models.TextField(verbose_name='文章正文')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='项目说明')),
                ('add_user', models.CharField(max_length=64, null=True, verbose_name='添加者')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分类名')),
                ('dev_group', models.CharField(blank=True, max_length=64, null=True, verbose_name='开发团队Leader')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='项目分类说明')),
                ('add_user', models.CharField(max_length=64, null=True, verbose_name='添加者')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dochandler.DocumentCategory', verbose_name='所属分类'),
        ),
    ]
